#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'
  cookbook 'firewall'
  cookbook 'apt'	
  cookbook 'mysql'
  cookbook 'database'
  cookbook 'java'

